name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Instal deps
      run: sudo apt install make build-essential git libglfw3 libglfw3-dev pkg-config
    - name: Submodules
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: check
      run: ulimit -t 1; ./Onix
